/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 windows_logo.glb -T 
Files: windows_logo.glb [298.14KB] > E:\Portfolio\public\models\windows_logo-transformed.glb [12.28KB] (96%)
Author: giMbo1-kafmyr-pynriv (https://sketchfab.com/giMbo1-kafmyr-pynriv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/windows-logo-fa4cbd1c4b104e24960d0281da2828ea
Title: Windows Logo
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/windows_logo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.path1_SVGMat089_0.geometry} material={materials['SVGMat.089']} scale={25.36} />
    </group>
  )
}

useGLTF.preload('/windows_logo-transformed.glb')
