/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cisco_logo.glb -T 
Files: cisco_logo.glb [327.06KB] > E:\Portfolio\public\models\cisco_logo-transformed.glb [23.43KB] (93%)
Author: Giannis Kepas (https://sketchfab.com/gkepas)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/cisco-logo-0a3b0e3ddf964f768504c22ccbed5604
Title: Cisco Logo
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cisco_logo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Cisco-Logo_Material007_0'].geometry} material={materials['Material.007']} rotation={[-Math.PI, 0, 0]} scale={0.16} />
    </group>
  )
}

useGLTF.preload('/cisco_logo-transformed.glb')
