/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tux.glb -T 
Files: tux.glb [1.2MB] > E:\Portfolio\public\models\tux-transformed.glb [106.71KB] (91%)
Author: Andy Cuccaro (https://sketchfab.com/andycuccaro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tux-157de95fa4014050a969a8361a83d366
Title: Tux
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tux-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Tux-printable_0'].geometry} material={materials.black} position={[0.002, -0.027, -0.719]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Tux-printable_1'].geometry} material={materials.white} position={[0.002, -0.027, -0.719]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Tux-printable_2'].geometry} material={materials.orange} position={[0.002, -0.027, -0.719]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/tux-transformed.glb')
